name: portal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  dynamic_color: ^1.8.1
  emoji_picker_flutter: ^4.4.0
  flex_seed_scheme: ^4.0.1
  flutter_hooks: ^0.21.3+1
  flutter_secure_storage: ^10.0.0
  hooks_riverpod: ^3.2.1
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  logger: ^2.6.2
  path_provider: ^2.1.5
  shadcn_ui: ^0.46.1
  socket_io_client: ^3.1.4
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
